version: '3'
services:
  db_postgres:
    image: postgres:14-alpine
    container_name: db-snb-prod
    restart: always
    environment:
      - POSTGRES_USER: ${POSTGRESQL_USER:-opensiuser}
      - POSTGRES_DB: 'snb-prod'
      - POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-opensi}
    volumes:
      - postgres: postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - snb
  
  migrate:
    build:
      context: ./backend/prisma
    image: registry.gitlab.com/opensi/snb-backend
    container_name: migrate-snb-prod
    environment:
      - DATABASE_URL=postgresql://opensiuser:opensi@db_postgres:5432/snb-prod
    depends_on:
      - db_postgres
    # command: npm run clean
    command: npm run migrate
    networks:
      - snb
  
  backend:
    build:
      context: ./backend
    image: registry.gitlab.com/opensi/snb-backend
    ports:
      - 8000:8000
    container_name: backend-snb
    environment:
      - DATABASE_URL=postgresql://opensiuser:opensi@db_postgres:5432/snb-prod
    networks:
      - snb
    depends_on:
      - db_postgres

  frontend:
    build:
      context: ./front
    image: registry.gitlab.com/opensi/snb-front
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - snb

volumes:
  postgres: ~

networks:
  snb:
